### **PART I**

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [2]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
vector = torch.tensor ([7,7])
vector

tensor([7, 7])

In [6]:
vector.shape

torch.Size([2])

In [7]:
MATRIX = torch.tensor ([[7,8], [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[0]

tensor([7, 8])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [4,2,3]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [4, 2, 3]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])

In [14]:
# Random tensors : The neural networks starts with tensor full of random numbers then they adjust those number to be better
rantensor = torch.rand(3,4, 6)
rantensor

tensor([[[7.3233e-02, 4.9844e-02, 9.1741e-02, 3.7996e-01, 8.7961e-01,
          1.5391e-01],
         [6.6834e-01, 4.0905e-01, 4.7917e-01, 2.6037e-01, 8.1779e-01,
          8.3007e-01],
         [8.1557e-01, 4.7168e-01, 3.1867e-01, 8.4337e-01, 9.2002e-01,
          5.4383e-01],
         [2.1418e-01, 7.9487e-01, 2.6865e-01, 2.4893e-01, 4.7018e-01,
          5.5642e-02]],

        [[1.1652e-01, 7.9178e-01, 3.3292e-01, 4.7711e-01, 6.4801e-01,
          4.5080e-01],
         [1.2890e-01, 1.1377e-01, 7.4919e-01, 9.3170e-01, 8.5947e-01,
          4.6442e-01],
         [1.2213e-01, 4.7897e-01, 3.3997e-01, 8.8036e-05, 8.6906e-01,
          4.8972e-01],
         [8.6661e-01, 2.4959e-01, 7.7689e-01, 7.1204e-01, 5.2394e-01,
          1.2152e-01]],

        [[3.4284e-01, 3.8732e-03, 7.0654e-01, 5.6354e-01, 8.6843e-01,
          1.7617e-01],
         [2.2713e-01, 1.5229e-01, 4.1732e-01, 1.3007e-01, 4.8935e-01,
          4.1530e-02],
         [3.9111e-01, 8.9801e-01, 1.9882e-01, 3.9371e-01, 7.7643e-

In [15]:
rantensor.ndim

3

In [16]:
#size = height, width, color channels
imgtensor = torch.rand(size = (224, 221, 3))
imgtensor.shape, imgtensor.ndim

(torch.Size([224, 221, 3]), 3)

In [17]:
#Zeros and one, for masking certain part
zero = torch.zeros(3,4)
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [18]:
one = torch.ones(3,4)
one
#either ones and zeros can be used for masking

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
one.dtype #the data type were using is float

torch.float32

In [20]:
#Range of tensors
torchtest = torch.arange(start = 0,  end = 120, step = 2)
torchtest

tensor([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
         28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,  54,
         56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,
         84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104, 106, 108, 110,
        112, 114, 116, 118])

In [21]:
#Tensor like or to duplicate other tensors
torchtest2 = torch.zeros_like(input = torchtest)
torchtest2

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
#Tensor datatype
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #what type you want to
                               device = None, #what device your tensor on
                               requires_grad=False #wether or not to track gradients with tensor
                               )
float_32_tensor
# there are 16, 32, and 64 type the higher it is the more accurate the tensor are but slower
# cannot change from 16 to 32
# the default type is 32 even if we inpu none

tensor([3., 6., 9.])

In [23]:
# changing to less accurate tensor
float_16 = float_32_tensor.type(torch.float16)
float_16
float_16 * float_32_tensor

tensor([ 9., 36., 81.])

In [24]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [25]:
# Multiplying tensor
new_tensor = int_32_tensor * float_32_tensor

In [26]:
# Getting info from tensor
# to get data type of tensor : tensor.dtype
# to get shape : tensor.shape
# to get device of tensor : tensor.device

new_tensor.dtype
random = torch.rand(3,4)
random

tensor([[0.1934, 0.8614, 0.7903, 0.4034],
        [0.3895, 0.2272, 0.5959, 0.5802],
        [0.8088, 0.0012, 0.6788, 0.6118]])

In [27]:
print(random)
print(f"Datatype of tensor: {random.dtype}")
print(f"Shape of tensor: {random.shape}")
print(f"Device tensor: {random.device} ")

tensor([[0.1934, 0.8614, 0.7903, 0.4034],
        [0.3895, 0.2272, 0.5959, 0.5802],
        [0.8088, 0.0012, 0.6788, 0.6118]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor: cpu 


In [28]:
#Tensor manipulation
# addition, subtract, multiplication (element-wise), division, matrix multiplication

randomnum = torch.tensor([1,3,4])
randomnum + 10

tensor([11, 13, 14])

In [29]:
#Multiply tensor by 10
randomnum * 10

tensor([10, 30, 40])

In [30]:
# substract
randomnum - 10

tensor([-9, -7, -6])

Tensor datatype

**3** things that will be most common error:
- Datatype (long, float,etc)
- Shape (3,2 or 3,4)
- Device (GPU or CPU)

In [31]:
# Multiplication of Matrixs
print(randomnum * randomnum)

tensor([ 1,  9, 16])


In [32]:
torch.matmul(randomnum, randomnum) #This is if we add all of the number on the tensor

tensor(26)

In [33]:
%%time
value = 0
for i in range(len(randomnum)):
  value += randomnum[i] * randomnum[i]
print (value)
# this is the manual multiplication of tensor which is longer and
# take a lot of code

tensor(26)
CPU times: user 1.77 ms, sys: 141 µs, total: 1.91 ms
Wall time: 1.7 ms


1. Remember that multiplication need same inner dimension to work
- (3,2) with (2,3) will work
- (3,2) with (3,2) wont work
2. The new matrix will have shape of the outer dimmernsion
- (2,3) with (3,2) will be (2,2)

In [34]:
torch.matmul(torch.rand(10,3), torch.rand(3,2))

tensor([[0.4171, 0.5844],
        [0.5874, 0.9102],
        [0.9014, 1.2166],
        [0.5481, 1.0146],
        [0.3321, 0.5510],
        [0.0604, 0.1221],
        [0.3631, 0.4982],
        [0.8448, 1.3204],
        [0.7960, 1.1631],
        [0.4171, 0.7961]])

In [35]:
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])
tensor_B = torch.tensor([[7,8],
                         [9,10],
                         [11,12]])



To fix the shape we can use the transpose
using the nametensor.T

In [36]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  9, 11],
         [ 8, 10, 12]]),
 torch.Size([2, 3]))

In [37]:
torch.matmul(tensor_A, tensor_B.T) #Now we can multiply the tensor A and tensor

tensor([[ 23,  29,  35],
        [ 53,  67,  81],
        [ 83, 105, 127]])

In [38]:
torch.matmul(tensor_A.T, tensor_B)

tensor([[ 89,  98],
        [116, 128]])

Tensor aggregation (mean, max, min, etc)

In [39]:
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
torch.min(x), x.max(x)

(tensor(0), tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [41]:
torch.mean(x.type(torch.float32)) #The mean function requires float32 so need to change it first from long

tensor(45.)

In [42]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

Finding positional of min and max

using .argmin()

In [43]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
x.argmin() #find the postion in tensor of the minimum value, where is the index

tensor(0)

In [45]:
x.argmax() #on the 9 index

tensor(9)

In [46]:
x[9] #what is the number of the 9 index

tensor(90)

Reshaping, stacking, squeezing and unsqueezing tensor

1. Reshape - reshape input tensore to a defined shape
2. View - return a view of an input tensor of certain shape but keep the same memory as original
3. Stacking - combine multiple tensors on top of each other or side by side
4. squeeze - remove all '1' dimension from a tensor
5. unsqueeze - add '1' dimension to a target tensor
6. permute - return a view of the input with dimension swapped in a certain way

In [47]:
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
## add extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape
# its changing to a 2 dimension

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [49]:
y = torch.arange(1., 15.)
y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14.]),
 torch.Size([14]))

In [50]:
y_reshaped = y.reshape(2, 7)
y_reshaped, y_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11., 12., 13., 14.]]),
 torch.Size([2, 7]))

In [51]:
# stack tensor
x_stacked = torch.stack([x,x,x,x], dim = 1)
x_stacked

tensor([[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [52]:
# squeeze tensor
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [53]:
x_reshaped.shape

torch.Size([1, 9])

In [54]:
x_squeezed = x_reshaped.squeeze()
# it removes 1 dimension

In [55]:
print("Before: ", x_reshaped)
print("With ", x_reshaped.shape)
print(" ")
print("After: ", x_reshaped.squeeze())
print("This one: ", x_reshaped.squeeze().shape)

Before:  tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
With  torch.Size([1, 9])
 
After:  tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
This one:  torch.Size([9])


In [56]:
# unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
x_unsqueezed

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [57]:
# permute (rearrange)
x = torch.randn(2,3,5)
x.size()
torch.permute(x, (2,1,0)).size() # its using the index of the number to move to other place


x_original = torch.rand(size=(224,224,3)) # Height, widht, channel
x_permuted = x_original.permute(2, 0, 1) # shift axis 0 -> 1, 1 -> 2, 2 -> 0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")
#it will shift on colour on the picture

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [58]:
x_original[0,0,0] = 1231312
x_permuted.shape

torch.Size([3, 224, 224])

Indexing (selecting data from tensor)
Use Numpy



In [59]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [60]:
# index on the outer bracket
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [61]:
# index on middle bracket
x[0][0]
# or
x[0,0]

tensor([1, 2, 3])

In [62]:
# index on inner bracket
x[0,0,0]

tensor(1)

In [63]:
x[0,2,0]
# select outer bracket, then middle bracket, then inner bracket start from 0

tensor(7)

In [64]:
# Can also use ":" to target all of the dimension
print(x[:, 2, 2])
print(x[:,:,1])
print(x[0,:,2])
# we got all of the dimension by using the : thats why we got the []

tensor([9])
tensor([[2, 5, 8]])
tensor([3, 6, 9])


Using the NumPy
- Data in NumPy, want in pytorch tensor -> torch.from_numpy(ndarray)
- pytorch tensor -> NumPy -> torch.Tensor.numpy()

In [65]:
import numpy as np

array = np.arange(1.,8.)
tensor = torch.from_numpy(array).type(torch.float32) # when converting from numpy to pytorch, pytorch reflec numpy default daatatype float64 while pytorch on float32
array, tensor                                        # so you need to change it to not have error

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [66]:
array.dtype
tensor.dtype

torch.float32

In [67]:
# change array value, what will it do to tensor
array = array + 1
array, tensor
#

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [68]:
# Tensor to numPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [69]:
# changing the tensor, what happen to 'numpy_tensor'?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

Reproducecibility (trying to take random out of random)

How neural network learn:
random num -> tensor operation -> update random number to make better data -> again . . .

To reduce randomness in NN comes concept of **random seed**

**random seed** = flavour of randomness

In [70]:
random_A = torch.rand(3,4)
random_B = torch.rand(3,4)

print(random_A)
print(random_B)
print(random_A == random_B)

tensor([[0.6884, 0.6179, 0.9923, 0.3436],
        [0.9477, 0.8901, 0.0608, 0.4077],
        [0.1818, 0.6561, 0.1565, 0.8460]])
tensor([[0.4459, 0.7033, 0.0396, 0.9225],
        [0.1475, 0.0902, 0.4284, 0.7489],
        [0.0232, 0.5167, 0.1539, 0.1651]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [71]:
# reproducible
random_seed = 42
# the number is for the “starting point” of the algorithm to be
# it will move from there and generate random numbers.
torch.manual_seed(random_seed)
random_seed_c = torch.rand(3,4)
torch.manual_seed(random_seed)
random_seed_d = torch.rand(3,4)

print(random_seed_c)
print(random_seed_d)
print(random_seed_c == random_seed_d)
# 'Flavoured' Randomness

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [72]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


**Excercises**